### ISSUE TITLE
How would I integrate this with typeform?

### ISSUE THREAD

**Issue by antecrypto** [kuyawa/PayWithStellar#3]
Hello,

How would I integrate paywithstellar with typeform? I want to be able to track the emails of those who paid. 

Thank you

**Comment by samuel-allan** [comment]
I don't think there is any functional integration yet (and I haven't been actively working on one), but this could be a good time to start. You still need a unit on the server which validates that the purchase has actually happened (the JS side simplifies the UI flow mostly, but you still need something in your server which validates the purchase and puts the email on the list). This server component is not yet present

**Comment by samuel-allan** [comment]
I don't know typeform, but I think it would be a good idea to consult what they have on their [site regarding the APIs](https://developer.typeform.com/). What are you having trouble with?
